Create nut.rst
opnsense/docs pull request #287
Opened 2020-10-06 15:30 UTC by Melantrix

There is almost no documentation about how to configure NUT. I needed some guidance on IRC to get it working because of that. To fix the real issue here (no documentation) this page is created to have at least a starting point on configuring NUT.

This is my first pull request and documentation page, so please let me know if i need to change anything, including following a different process or something!

2020-10-07 07:40 UTC, mimugmail requested changes
Small things, thx for starting this!

2020-10-07 07:40 UTC, mimugmail commented on source/manual/how-tos/nut.rst
> +NUT is available as a plugin in OPNSense via the plugin **os-nut**. You can install the plugin via **System > Firmware > Plugins > os-nut**. After installation NUT will be available as a service, you
OPNsense, I'd remove the second sentence. Usually a refresh is enough.

2020-10-07 07:40 UTC, mimugmail commented on source/manual/how-tos/nut.rst
> +*Please add standalone documentation if you have configured this yourself.*
Can you remove this section? We can't publish this unfinished. I'll take care of the rest ...

2020-10-07 07:40 UTC, mimugmail commented on source/manual/how-tos/nut.rst
> +4. Click on **Diagnostics** in the left menubar. If configured correctly this page will show, after waiting a few seconds, information about the UPS. Loook for **device.mfr** and **device.model** to
Maybe you can also add a screenshot for this?

2020-10-07 07:49 UTC, Melantrix commented on source/manual/how-tos/nut.rst
> +NUT is available as a plugin in OPNSense via the plugin **os-nut**. You can install the plugin via **System > Firmware > Plugins > os-nut**. After installation NUT will be available as a service, you
Done!

2020-10-07 07:54 UTC, Melantrix reviewed
I've changed the file like you suggested, thanks for reviewing!

2021-01-11 16:35 UTC, merged

2021-01-11 16:36 UTC, AdSchellevis commented
@Melantrix thanks! pulling this state in now, if you want to extend it later, just open a new PR