Updated instructions to match GCP interface
opnsense/docs pull request #352
Opened 2021-09-17 12:45 UTC by adamhogle

Resolves #351.

2021-09-17 12:52 UTC, fichtner commented
CC @Greelan (can't add you as reviewer without adding you to org, maybe you would like an invite?)

2021-09-17 12:55 UTC, Greelan commented
Sure, happy to review 😀

2021-09-17 13:00 UTC, fichtner commented
@Greelan much better, thanks :D

2021-09-17 22:57 UTC, Greelan requested changes
Thanks very much for taking the time to suggest updates. It's unfortunate that Google seems to like playing with its UI a lot!

I've suggested some changes to your PR with the aim of making it simpler.

2021-09-17 22:57 UTC, Greelan commented on source/manual/how-tos/cloud_backup.rst
I think these two steps can be simplified by just directing the user directly to the service account page. So first delete the Credentials page step (the corresponding image `google_create_credentials.png` can also be deleted).

```suggestion
```

2021-09-17 22:57 UTC, Greelan commented on source/manual/how-tos/cloud_backup.rst
> +-  On the Credentials page, click the **Manage service accounts** hyperlink that appears next to the Service Account table:
Then direct the user to search for "service accounts" and go directly to the page. I have attached a replacement screenshot for `google_select_service_account.png`, which will need to be substituted: ![google_select_service_account](https://user-images.githubusercontent.com/53196309/133861481-99f53c35-3ad8-434b-9e48-0895b5da32ba.png)).

```suggestion
-  Now create a service account for your project. In the search bar at the top of the page, search for “service accounts" and click on the corresponding search result:

```

2021-09-17 22:57 UTC, Greelan commented on source/manual/how-tos/cloud_backup.rst
> +1. Set up a Google Drive folder
This change is not correct, as creating the Google Drive folder is the second step. The first step is creating the Google project.

```suggestion
2. Set up a Google Drive folder
```

2021-09-19 01:57 UTC, adamhogle commented on source/manual/how-tos/cloud_backup.rst
Done.

2021-09-19 01:58 UTC, adamhogle commented on source/manual/how-tos/cloud_backup.rst
> +-  On the Credentials page, click the **Manage service accounts** hyperlink that appears next to the Service Account table:
I agree, this is a much easier way to get to this, and it should change less in the future.

2021-09-19 01:59 UTC, adamhogle commented on source/manual/how-tos/cloud_backup.rst
> +1. Set up a Google Drive folder
This was an unintended change that I missed when preparing the PR. I've reverted the code.

2021-09-19 02:04 UTC, Greelan approved these changes
Looks good, thanks!

2021-09-19 06:48 UTC, fichtner commented
Merged, thanks!

2021-09-19 06:48 UTC, merged