Update to install.rst
opnsense/docs pull request #456
Opened 2023-02-22 07:49 UTC by linuxdude21

First-half installation page change.  I wanted to know what you all think before continuing to update the 2nd half of the installation guide. The biggest changes are the order (flow) of the install guide and OPNsense Importer.

Order:  The page first talks about Image types then jumps to Download & verification (should be closer to the installation section), and then back to installation Media, naming, etc.  The flow in this change is installation images/media, downloading, verifying, and installing.

OPNsense Importer: Complete rewrite to give direction on how to use it.

Removals:
LibreSSL vs OpenSSL
Cut back on the directions for downloading image files, as the previous directions failed after step 2.  Most browsers today download even if you right-click and open in a new tab. (lands signed and verified in the GUI of the running software) Updates:
Installation Media adding Image Type column
add openssl checksum step

2023-02-22 07:56 UTC, fichtner commented on source/manual/install.rst
> +All images have the OPNsense Importer feature that offers great flexibility in
Technical docs should avoid opinions and exaggeration, "great" is one of those and can easily be dropped

2023-02-22 07:57 UTC, fichtner commented on source/manual/install.rst
> +configurations without installing.
closer to the point: without overwriting the current installation by running the new version in memory with the existing configuration

2023-02-22 07:58 UTC, fichtner commented on source/manual/install.rst
> +1. You must have a 2nd USB drive formatted with FAT or FAT32 File system.
The early importer can import from USB stick, but also just from the installed disk... (see point above)

2023-02-22 07:59 UTC, linuxdude21 commented on source/manual/install.rst
> +All images have the OPNsense Importer feature that offers great flexibility in
I completely agree.  It is an excellent feature if you ever have to recover a bad firewall.

2023-02-22 08:00 UTC, fichtner commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
backup and configuration xml are the same, perhaps shorten to "configuration"

2023-02-22 08:00 UTC, linuxdude21 commented on source/manual/install.rst
> +recovering failed firewalls quickly or testing new releases with existing
understood.

2023-02-22 08:05 UTC, linuxdude21 commented on source/manual/install.rst
> +configurations without installing.
All images have the OPNsense Importer feature that offers flexibility in recovering failed firewalls or testing new releases without overwriting the current installation by running the new version in memory with the existing configuration.

Better?

2023-02-22 08:09 UTC, linuxdude21 commented on source/manual/install.rst
> +1. You must have a 2nd USB drive formatted with FAT or FAT32 File system.
Oh, I see, I didn't realize that.  Just to be clear "Installed disk", means the existing drives from a previous installation?

2023-02-22 08:12 UTC, linuxdude21 commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
Well really two points here, you can use either a backup XML or a copy /conf/config.xml "configuration".  Another thing is you can encrypt backups, but you can't use encrypted .xml with the Importer.

2023-02-22 08:23 UTC, fichtner commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
yes, that's basically the idea of requiring a /conf directory to be present to import :)

2023-02-22 08:23 UTC, fichtner commented on source/manual/install.rst
> +1. You must have a 2nd USB drive formatted with FAT or FAT32 File system.
yes, that's basically the idea of requiring a /conf directory to be present to import :)

2023-02-22 08:24 UTC, fichtner commented on source/manual/install.rst
> +configurations without installing.
yep

2023-02-22 08:28 UTC, fichtner commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
it's a bit more complex: the backups are just copies of the authoritative config.xml from an older point in time. You can also import backups but these reside in /conf/backups directory and are only used when switching to them via GUI or console. The main config.xml is a configuration XML obtained somehow or edited otherwise and of course unencrypted as the decryption was not implemented for several reasons in this end of the system.

2023-02-22 08:32 UTC, fichtner commented on source/manual/install.rst
> ++--------+---------------------------------------------------+------------+
nice addition, thanks!

2023-02-22 08:33 UTC, fichtner commented on source/manual/install.rst
> +  and re-writes. For embedded (nano) versions memory disks for **/var** and **/tmp** are
Nowadays this is:

```suggestion
  and re-writes. For embedded (nano) versions memory disks for **/var/log** and **/tmp** are
```

2023-02-22 08:34 UTC, fichtner commented on source/manual/install.rst
> -OpenSSL and LibreSSL
nice catch ;)

2023-02-22 08:35 UTC, fichtner commented
Thanks for doing this! I'll probably nag here quite a bit but really appreciate the help. Apologies in advance :)

2023-02-22 08:40 UTC, linuxdude21 commented on source/manual/install.rst
> +Since version 15.1.10 (04 May 2015) the option to install an
Completely agree with the reference and kinda see your later point.   Merge the embedded/full with installation Media is the question?

2023-02-22 08:50 UTC, linuxdude21 commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
Sorry you know the backend of the system more than me.  But from an end user, GUI-based user mostly, I know nothing of the /conf/backups/.  When I talk about backup.xml.  I'm referencing to the exported backups from the System > Configuration > Backups.  "Download configuration" button.  Place that file on a USB drive and use Importer in that context.  Maybe I should organize Importer into two functions, new installation using a backup.xml, and firewall recovery/testing new releases using existing /conf/config.xml on an installed drive?

2023-02-22 08:54 UTC, fichtner commented on source/manual/install.rst
> +Since version 15.1.10 (04 May 2015) the option to install an
Merge first and second paragraph, yes. Trouble is the point it is trying to make is weak: embedded exist, full can be installed anywhere -- I don't have a better idea at the moment though.

2023-02-22 08:57 UTC, fichtner commented on source/manual/install.rst
> +3. Put an unencrypted backup xml or configuration xml into /conf and rename the file to **config.xml**
well, my initial point about only using "configuration"... perhaps "previously exported configuration" or downloaded... just to be precise about the source and not the type of the configuration (backup vs. main)

Yes, first section for existing installs (shorter) and then second section for preparing a USB stick for import (e.g. new install where you don't have a previous install on the disk you want to retain)

2023-02-22 08:57 UTC, linuxdude21 commented
No nags at all, I appreciate the insights.  No apologies are needed at all.  I want to know if I'm heading in the right direction.  One bit of help I'm going to need on my side is the proper use of Github.  Do I make these corrections on my local doc and update this pull request?  Honestly, this is the part of Github I just don't understand, forking, push/pulls requests.

2023-02-22 08:58 UTC, fichtner commented
The git branch is basically the GitHub PR... you add more changes locally, commit them on top and push to same branch to make the additions appear here.

2023-02-22 09:16 UTC, linuxdude21 commented on source/manual/install.rst
> +Since version 15.1.10 (04 May 2015) the option to install an
I see your point on those two lines.  However, I didn't do any rewriting as I don't fully understand both lines.  Or should I say the contrast between both lines?  I just reorder the lines to match the Embedded vs Full, and the table below [ Embedded | Full ].   

Isn't the intended purpose of embedded more of the preinstall aspect?  "I'm going to download this image, write it to disk, install that disk into the firewall, and boot (no installation process per se).  Due to the nature of flash memory, do we run embedded versions in RAM drives?

2023-02-22 09:24 UTC, fichtner commented on source/manual/install.rst
> +Since version 15.1.10 (04 May 2015) the option to install an
You are right, embedded image is a preinstalled image. That's the main difference. It's tailored to reduce write cycles as well, but can be used anywhere. Maybe that would be a good addition to these paragraphs.

2023-02-24 03:56 UTC, linuxdude21 commented
Hey folks, Sorry if I'm doing too many PRs.  Please let me know if that is unwanted.  Or I should follow a different process? 

Also, would like to know if I'm going in the right direction.  I don't want to send a bunch of edits that are completely unusable or not accepted.  Thanks Nick,

2023-02-24 09:33 UTC, AdSchellevis commented
@linuxdude21 we'll try to discuss next week how we can move this one to a merge, but so far the process from my end looks normal. Just open a new PR (branch) when working on a new topic. When processing feedback, we're used to kep the original one open until it's finished. It has been a busy week, these things sometimes just take time.

2023-02-24 23:25 UTC, linuxdude21 commented
@AdSchellevis & @fichtner Thank you for the replies.  When I first got into this, I had a very mild idea of what things I wanted to update.  Few section updates, and minor re-ordering.  After that last few nights, it's turning into a complete reordering of the sections.  With most sections needing some form of updating.  I don't mind putting in the time/effort, just don't want it to go to waste because I'm headed in the wrong direction.  Please ignore me I'm sure you have bigger fish to fry.  Have a great weekend!

2023-02-25 09:51 UTC, AdSchellevis requested changes

2023-02-25 09:51 UTC, AdSchellevis commented on source/manual/install.rst
> +   For nano images is console access required?
it's practical, but when written to a sd card and it boots normally, strictly you don't need it.

2023-02-25 09:51 UTC, AdSchellevis commented on source/manual/install.rst
> +  `README <https://pkg.opnsense.org/releases/mirror/README>`.  You are encourage to updated
> encourage

encouraged ?

2023-02-25 09:51 UTC, AdSchellevis commented on source/manual/install.rst
> +OSes and for Windows use physdiskwrite or `Etcher <https://www.balena.io/etcher#download-etcher>`_.
quite some people seem to face challenges with `physdiskwrite` thanks for addressing this, maybe we could also add Rufus (https://rufus.ie/nl/) as an option, that seems to be the other popular option.

2023-02-25 09:51 UTC, AdSchellevis commented on source/manual/install.rst
> +   use the 2nd interface as a default LAN interface using DHCP on 192.168.1.x network?
The interface configuration should be the same, the build system only "curries" it with memory/console settings (https://github.com/opnsense/tools/blob/fce1fe3fe006dba02be284e86430bf3d2ad9d892/config/23.1/extras.conf#L69-L73) if I'm not mistaken.

Moving the item is probably ok, from the text review it's a bit difficult to envision the final layout in my head.

2023-02-25 09:51 UTC, AdSchellevis commented on source/manual/install.rst
> +
see previous comment.

2023-02-25 09:57 UTC, AdSchellevis commented
> @AdSchellevis & @fichtner Thank you for the replies. When I first got into this, I had a very mild idea of what things I wanted to update. Few section updates, and minor re-ordering. After that last few nights, it's turning into a complete reordering of the sections. With most sections needing some form of updating. I don't mind putting in the time/effort, just don't want it to go to waste because I'm headed in the wrong direction. Please ignore me I'm sure you have bigger fish to fry. Have a great weekend!

@linuxdude21 I've left some small remarks and answers to some of your questions, really love what you're doing with the page. In my humble opinion the sections aren't set in stone, if shifting makes it better readable, we should certainly do so. The only thing that for the whole documentation is more or less fixed is the main menu organization, as that matches most of the product menu layout.  I probably want to do a final review after we pulled it in and build the html, sometimes you notice things in its final shape.

2023-02-27 13:37 UTC, linuxdude21 commented on source/manual/install.rst
> +OSes and for Windows use physdiskwrite or `Etcher <https://www.balena.io/etcher#download-etcher>`_.
Personally, I've only used phydiskwrite to confirm this install guide.  When using windows, I feel most users would stick to GUI-based tools.  Of course, I think Windows is adopting Linux tools.  Bash cli integration come win12 or 13, I bet.  haha  Should we remove phydiskwrite, and replace that with Etcher and Rufus?  

I will get Rufus added.  Should I get screenshots of both?

2023-02-27 13:47 UTC, linuxdude21 commented on source/manual/install.rst
> +
Thank you and apology I haven't used the nano image before.  Do we think it's best to list out the default settings for the user to connect to the firewall after booting up?  I'm thinking this would be an extreme use case where the user flashes the image to the drive, installs, and boots without some type of console.

2023-02-27 13:51 UTC, linuxdude21 commented on source/manual/install.rst
> +  `README <https://pkg.opnsense.org/releases/mirror/README>`.  You are encourage to updated
I had this fixed, it reads: We are encouraged to update OPNsense after installation to be on the latest release available

2023-02-28 10:49 UTC, fichtner commented on source/manual/install.rst
> +OPNsense offers two Image Types with all Major releases, Embedded (nano) Image
I'd prefer lowercase when not referencing a trademark or otherwise wanting to highlight it. Serial, VGA, Nano and DVD work for me as image names. Makes it a little easier to process them.

```suggestion
OPNsense offers two Image types with all major releases: embedded and full images. [etc]
```

2023-02-28 10:54 UTC, fichtner commented on source/manual/install.rst
> +The main differences between an Embedded (nano) image and a Full images are:
Ideally we shouldn't confuse users with "nano" vs. embedded before the table below. Afterwards, "full" and "embedded" should no longer be references and the real image names should be used instead when required.

2023-02-28 14:07 UTC, linuxdude21 commented on source/manual/install.rst
> +The main differences between an Embedded (nano) image and a Full images are:
So before the table, the image should be referred to as embedded or nano?

2023-03-01 03:23 UTC, linuxdude21 commented on source/manual/install.rst
> +   use the 2nd interface as a default LAN interface using DHCP on 192.168.1.x network?
@AdSchellevis thank you for the reply.  But I'm not sure what I'm looking at in that link.  In my PR I have already moved the nano section and rewrote 80% of it.  I will boot up a nano image.  I believe the defaults are like full image defaults, LAN @ 192.168.1.1/24 on the first NIC, with DHCP pool, DNS, & WebGUI enabled. WAN on 2nd NIC w/DHCP IP.  

Thanks,

2023-03-01 03:30 UTC, linuxdude21 commented on source/manual/install.rst
> +The main differences between an Embedded (nano) image and a Full images are:
After rereading your reply, we want to reference embedded before the table. Please let me know if I'm wrong.  I have already update.

2023-03-03 14:36 UTC, fichtner commented on source/manual/install.rst
> +and Full Images.  The Embedded Image is intended for environments where preinstalling
looks like copy/paste error

```suggestion
OPNsense offers two Image types with all major releases: embedded and full images.
The Embedded Image is intended for environments where preinstalling 
```

2023-03-03 14:38 UTC, fichtner commented on source/manual/install.rst
> +The main differences between an Embedded (nano) image and a Full images are:
simplify:

```suggestion
The main differences between embedded and full images are:
```

2023-03-03 14:39 UTC, fichtner commented on source/manual/install.rst
> +Embedded (nano) image store logging and cache data in memory only, while Full versions
```suggestion
Embedded image store logging and cache data in memory only, while full versions
```

2023-03-03 14:40 UTC, fichtner commented on source/manual/install.rst
> +| vga    | USB image (.img) boots into a live environment    | Full       |
```suggestion
| vga    | USB image boots into a live environment           | Full       |
```

2023-03-03 14:41 UTC, fichtner commented on source/manual/install.rst
> +   embedded (nano) versions memory disks for **/var/log** and **/tmp** are applied by
```suggestion
   Nano image memory disks for **/var/log** and **/tmp** are applied by 
```

2023-03-03 14:42 UTC, fichtner commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
```suggestion
   To reverse this behaviour go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`, 
```

2023-03-03 14:44 UTC, fichtner commented on source/manual/install.rst
> +Installation Media
Is this a typo? We already had "media"?

2023-03-03 14:45 UTC, fichtner commented on source/manual/install.rst
> +Installation Media
Perhaps change this to "Installation media preparation" or similar to match next heading

2023-03-03 14:46 UTC, fichtner commented on source/manual/install.rst
> +GUI or even SSH directly. If a timeout was missed, restart the boot procedure.
```suggestion
GUI or even SSH directly. If the importer timeout was missed, restart the boot procedure.
```

2023-03-03 14:46 UTC, linuxdude21 commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
This was on the original install page.  I believe who wrote was telling everyone you can make full image installations operation like nano images.

2023-03-03 14:47 UTC, linuxdude21 commented on source/manual/install.rst
> +Installation Media
No, not in my suggestion to change the sections.  I renamed a few sections.  This was the first one.

2023-03-03 14:48 UTC, fichtner commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
I know but I'm trying to get rid of "embedded" below the image table with the full/embedded column. From this point on "full" and "embedded" should be avoided.

2023-03-03 14:50 UTC, linuxdude21 commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
"To enable full versions" ?

2023-03-03 14:52 UTC, linuxdude21 commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
When you are referencing two different items.  In this case, Nano vs Full images.  We should capitalize the first letter.  I will take your lead.

2023-03-03 14:52 UTC, fichtner commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
well, yes but without either "embedded" or "full".

2023-03-03 14:54 UTC, fichtner commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
capitalizing breaks the reading flow for me. For Nano, VGA, Serial and DVD it makes sense, for everything else not.

2023-03-03 15:11 UTC, linuxdude21 commented
@fichtner Thank you for your edits.  Not a problem. Post-merge is the only way to see these suggested changes.  The most significant change is the flow of the doc.  I have not finished the last Section, "Initial Configuration".  As I wanted to focus more on the installation side of things.  One my steps was to get a nano image up and running and fell into a rabbit whole with NAT.


Unrelated to the install doc:
Where I found a significant flaw in NATing.  Not sure if this is a bug or not: [my post on the issue](https://forum.opnsense.org/index.php?topic=32760.0) But doing a simple Port Forward with an associated filter does not work.

2023-03-03 15:20 UTC, linuxdude21 commented on source/manual/install.rst
> +   To enable non-embedded versions: Go to :menuselection:`System --> Settings --> Miscellaneous --> Disk / Memory Settings`,
Again, I'll take your lead on this.  But breaking the flow of the reader is precisely the effect people need.  To know there is a difference between the two.  Remember, good man, you know this stuff WELL.  People reading this install guide have no clue.  They are still wrapping their minds around OPNsense.  ;)

2023-03-03 15:35 UTC, linuxdude21 commented on source/manual/install.rst
> +Installation Media
> Perhaps change this to "Installation media preparation" or similar to match next heading

Download and Verification are also parts of media preparation, which comes before Installation Media.  So I don't like that it.   But will take your lead if that's the case.

2023-03-03 15:37 UTC, linuxdude21 commented on source/manual/install.rst
> +   use the 2nd interface as a default LAN interface using DHCP on 192.168.1.x network?
So I have already moved the section and will boot up a nano image to see the defaults.  I will make future suggestions or have questions

2023-03-03 15:38 UTC, linuxdude21 commented on source/manual/install.rst
> +OSes and for Windows use physdiskwrite or `Etcher <https://www.balena.io/etcher#download-etcher>`_.
@AdSchellevis remove physdiskwrite? Again I've never used it before myself.  Windows users are going to have much more success with Etcher and Rufus.

2023-03-04 09:26 UTC, merged

2023-03-04 09:40 UTC, AdSchellevis commented
@linuxdude21 thanks a lot for the updates, made some small changes in https://github.com/opnsense/docs/commit/349fed697443d82177f29cdf57e75644ea9debad (links and added an index due to the length of the page). Results are already published online https://docs.opnsense.org/manual/install.html

About your forum question, I see there's communication there, one tool that's always very helpful when debugging issues is the packet capture in interface/diagnostics (apart from the live log you're already using).

2023-03-06 07:35 UTC, linuxdude21 commented
@AdSchellevis Wow, you already merged.  HAHA this is great.  Several items were missed. I believe that's my fault, as I started using comments within the doc.  With all my edits, they were easy to miss.  I submit another PR.  I finally got the upstream master to update my local repo.  Still trying to under github/repos.  

Thank you for the packet capture suggestion. I had already used it on this problem.  I saw the firewall sending the packet out the WAN interface, but my client never got them.  Franco got the problem disable reply-to on WAN, but I still question why that setting is enabled by default.  Another topic for a different day.  Thanks again, guys.

2023-03-06 07:43 UTC, AdSchellevis commented
@linuxdude21 ok, let's try to finish this as soon as possible then. 

The default reply-to//route-to is mostly for historic reasons, when using multiwan setups you do need to know where to return packets to as default routing doesn't apply. These rules ar a bit wider than you might want, but without adding a lot of hard to follow complexity not really solvable. When not using multi-wan, it's always safe to disable both, when you do need multiwan and "on net" traffic, you just need additional rules to make that explicit (disabling the reply-to).