Small grammar & layout fixes on BE page
opnsense/docs pull request #577
Opened 2024-07-10 15:51 UTC by melroy89

See title.

2024-07-10 15:59 UTC, AdSchellevis requested changes

2024-07-10 15:59 UTC, AdSchellevis commented on source/be.rst
> +Currently, the only open-source LINCE compliant firewall.
I don't  think a hyphen is needed for open source (https://en.wikipedia.org/wiki/Open_source)

2024-07-10 15:59 UTC, AdSchellevis commented on source/be.rst
> +* Official OPNsense Open Virtualization Image
we prefer British english, in which case an `s` is used

2024-07-10 16:36 UTC, melroy89 commented on source/be.rst
> +* Official OPNsense Open Virtualization Image
ah that is fine. OK

2024-07-10 16:37 UTC, melroy89 commented on source/be.rst
> +Currently, the only open-source LINCE compliant firewall.
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source

2024-07-10 16:39 UTC, melroy89 commented on source/be.rst
> +Currently, the only open-source LINCE compliant firewall.
Since it's a noun, I do believe you could/can use hyphenate the word open source as in open-source software or in this case open-source LINCE compliant firewall .

2024-07-10 17:05 UTC, AdSchellevis commented on source/be.rst
> +Currently, the only open-source LINCE compliant firewall.
I don't think either spelling is wrong, but if both are correct, it's a matter of preference in which case we can keep it like it is. (I don't have a strong preference, but also like to prevent the next guy opening a PR in a year or two to change it back)

2024-07-11 09:18 UTC, melroy89 commented
@AdSchellevis You should be able to merge it now.

2024-07-11 09:30 UTC, merged