system/snapshots: Add initial documentation for boot environments
opnsense/docs pull request #597
Opened 2024-09-02 15:24 UTC by Monviech

Fixes: https://github.com/opnsense/docs/issues/592

2024-09-02 15:27 UTC, Monviech commented
@SeimusS Can you give this a look? I tried to stay pragmatic in these docs, giving people what I think they need when they require Snapshots.

2024-09-02 15:35 UTC, fichtner commented
The idea was to ping @sheridans but more eyes are better ;)

2024-09-02 15:47 UTC, Monviech commented
@fichtner Oops but the more the merrier. :)

2024-09-02 16:14 UTC, SeimusS commented
Well you looped me so here is my feedback :)


**Quick Overview**

> Boot Environments require ZFS as filesystem. UFS will not work since it does not support file system level snapshots.

I would change the first "NOTE" to "Important" in the quick overview so it pokes into peoples eyes

**Recommended Workflow**
Is it necessary, to activate the new Snapshot? isn't better to continue on the current active = default and in case of problems to rollback on the created one?

Also depending on the issues that can be experienced rollback can be as well GUI, I think explixitly pointing to do it via CLI in boot menu may create a bit stress for some users (believe me or not I know few people that are scared to type cat command in the CLI)

**Creating a Snapshot**
I think this sentence is bit confusing >

> Now, there should be one Snapshot named default which is Active N, and a new Snapshot with a timestamp that is Active R.

Because >
N means "active now"
R means "active on reboot"

Regards,
S.

2024-09-03 05:16 UTC, Monviech commented
@SeimusS Thanks for the feedback.

- Changing the first note to attention would be a good choice
- For the workflow, I have used this as source, it seems to make sense: https://forums.FreeBSD.org/threads/bectl-confusion.85295/post-568756
- I'll make the sentence about the "Active" more clear
- My target audience were system administrators who do an upgrade of a hardware appliance. They should not be scared of the Boot Menu (I think)

2024-09-03 07:25 UTC, AdSchellevis requested changes

2024-09-03 07:25 UTC, AdSchellevis commented on source/manual/snapshots.rst
> +.. Note:: Each Snapshot can be created and deleted as its own self contained entity with no other dependencies. For practical reasons, it is recommended to keep no more than two *Snapshots*. Snapshot
Why two? If I'm not mistaken the storage amount used is similar if snapshots "stack", so, when it looks like this in time:

```
[1] ---------------------- [2] 
```

It would roughly require the same as 

```
[1] ----------[2]---------- [3] 
```

As the distance between 1 and 3 is the same as the distance (in bytes) between 1 and 2 of the earlier example. This obviously changes when [1] is forked multiple times, like:

```
   [1] ------ [2] ------- [3]
             \
              ------- [4] 
                             \
                              ---- [5]
```

2024-09-03 07:25 UTC, AdSchellevis commented on source/manual/snapshots.rst
> +    * Select the old *default* Snapshot in the Boot Menu
if you still are able to boot, you might want to prevent using the boot menu and just press "active" in the ui (and reboot).  In most cases you're likely still able to use the gui, it's just not what you expected.

2024-09-03 08:40 UTC, SeimusS commented
>     * Changing the first note to attention would be a good choice
This is just eye candy but from my experience of writing documentation it makes Huge difference

>     * For the workflow, I have used this as source, it seems to make sense: https://forums.FreeBSD.org/threads/bectl-confusion.85295/post-568756
It may and it does, but it doesn't mean its optimal. The less steps is required to do something the less is the probability of a user mistake. Simplicity is what should be targeted if possible or to try to crate simplicity. From What I read here for me it looks like there are just unnecessary steps than can create in some scenario for some people problems thus mistakes.

I overall think the snap should be create as rollback, and only be activated in case of problems.

This is the beauty of writing documentation, you can by your own experience create more optimal version.

>     * I'll make the sentence about the "Active" more clear
Thanks!
 
>     * My target audience were system administrators who do an upgrade of a hardware appliance. They should not be scared of the Boot Menu (I think)
Thats true, but keep in mind the OPNsense audience is more than just system or network admins. There is a lot of beginners newcomers that will use this feature ;)

@Monviech 

Regards,
S.

2024-09-03 09:23 UTC, Monviech commented
@SeimusS I have rewritten most of it to improve the logic and make it a bit more beginner friendly. Maybe its better now than before?

2024-09-03 09:47 UTC, SeimusS commented
@Monviech 

I was just looking at it, now looks much more beginner friendly and simpler (and hopefully less prompt to beginners mistake).
I like it!

One question tho, in the docs is mentioned snap will rollback
A. OS version in case upgrade was happened
B. Configuration changes/differences

Will the rollback of snap, rollback as well any installed packages, custom scripts (like those in rc. & syshook) etc? Because if yes maybe it would be good explicitly point what is part of the rollback and what is not. Cause this may sounds stupid, but I can imagine a situation where an user may ask these questions on forum (best case scenario) or assume it will/will not and than be surprised (worst case scenario) and open a topic on the forum. Could cause a bit of Catch-22 scenario.

Regards,
S.

2024-09-03 10:16 UTC, Monviech commented
Hmm...

@fichtner is the kernel a part of a boot environment?

If an upgrade includes a kernel update, would the old kernel need to be manually selected in the Boot Menu in addition to the Boot Environment?

2024-09-03 10:23 UTC, fichtner commented
The kernel is also stored on the ZFS BE. How the boot loader handles this half-way switching BEs and also switching kernels I don't know but it doesn't matter for the GUI use case we want to document.

2024-09-03 16:09 UTC, Monviech commented
Let's go for it, if anybody has improvements, PRs are welcome.

Merge discussed with @AdSchellevis

2024-09-03 16:10 UTC, merged