Clarify backend options, add missing options
opnsense/docs pull request #611
Opened 2024-10-12 17:26 UTC by ilumos

Today I switched my dual-stack firewall over from the legacy `ddclient` backend to the `native` backend, and I hope this update to the docs will help others do the same with ease. Thank you

2024-10-13 09:03 UTC, AdSchellevis requested changes
@ilumos some small remarks, rest looks fine, thanks

2024-10-13 09:03 UTC, AdSchellevis commented on source/manual/dynamic_dns.rst
> -      provider in the settings tab.
we might want to leave some note between the relation of the "check ip method" and the protocol being used.

2024-10-15 20:58 UTC, ilumos commented
Thanks @AdSchellevis, I've implmenented your improvement suggestions.

Regarding the note on protocols, did you see lines 64 to 69, which clarifies how to set up for dual stack?

2024-10-16 05:33 UTC, merged

2024-10-16 05:34 UTC, AdSchellevis commented
@ilumos I just did, thanks.

2024-10-17 21:05 UTC, ilumos commented
Awesome, thank you!